"""Pydantic v2 schemas for the Cinematographer Agent platform."""

from cinematography_schema.schema import (
    Action,
    CameraMovement,
    CameraFeed,
    Character,
    CinematicBeat,
    DialogueLine,
    DroneStatus,
    EmotionalTone,
    ResearchSource,
    SceneAnalysis,
    Shot,
    ShotPlan,
    ShotType,
    Simulation,
    SimulationState,
    Trajectory,
    Vector3,
)

from cinematography_schema.auth import (
    SubscriptionTier,
    TIER_PROJECT_LIMITS,
    RegisterRequest,
    LoginRequest,
    TokenPair,
    LoginResponse,
    RefreshRequest,
    TwoFactorLoginVerifyRequest,
    TwoFactorSetupResponse,
    TwoFactorEnableRequest,
    TwoFactorEnableResponse,
    TwoFactorDisableRequest,
    BackupCodesRegenerateResponse,
    UserOut,
    ProjectQuotaOut

)
__all__ = [
    "Action",
    "CameraMovement",
    "CameraFeed",
    "Character",
    "CinematicBeat",
    "DialogueLine",
    "DroneStatus",
    "EmotionalTone",
    "ResearchSource",
    "SceneAnalysis",
    "Shot",
    "ShotPlan",
    "ShotType",
    "Simulation",
    "SimulationState",
    "Trajectory",
    "Vector3",
    # Auth Schema
    "SubscriptionTier",
    "TIER_PROJECT_LIMITS",
    "RegisterRequest",
    "LoginRequest",
    "TokenPair",
    "LoginResponse",
    "RefreshRequest",
    "TwoFactorLoginVerifyRequest",
    "TwoFactorSetupResponse",
    "TwoFactorEnableRequest",
    "TwoFactorEnableResponse",
    "TwoFactorDisableRequest",
    "BackupCodesRegenerateResponse",
    "UserOut",
    "ProjectQuotaOut",
]
