"""add project

Revision ID: dc565ddc1a6b
Revises: f89d4e82bb8e
Create Date: 2026-08-28 12:09:26.886793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc565ddc1a6b'
down_revision: Union[str, Sequence[str], None] = 'f89d4e82bb8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('project_id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.add_column('scenes', sa.Column('project_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_foreign_key(None, 'scenes', 'projects', ['project_id'], ['project_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scenes', type_='foreignkey')
    op.drop_column('scenes', 'project_id')
    op.drop_table('projects')
    # ### end Alembic commands ###
