"""add scene style reference

Revision ID: f89d4e82bb8e
Revises: a6d7a23c8b3f
Create Date: 2026-08-26 14:04:04.013482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f89d4e82bb8e'
down_revision: Union[str, Sequence[str], None] = 'a6d7a23c8b3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenes', sa.Column('style_reference', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenes', 'style_reference')
    # ### end Alembic commands ###
